"""
Django settings for Qshop project.

Generated by 'django-admin startproject' using Django 2.1.8.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '!2l^kamqf$71!g5pu3u@4xl-a3&8enj0!@ll^2ssno(@u@3hm#'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Buyer',
    'Seller',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Qshop.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Qshop.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

# LANGUAGE_CODE = 'en-us'
LANGUAGE_CODE = 'zh-hans'

# TIME_ZONE = 'UTC'
TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

# USE_TZ = True
USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = (os.path.join(BASE_DIR, 'static'),)
# STATIC_ROOT = os.path.join(BASE_DIR, 'static')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'static')

DING_URL = 'https://oapi.dingtalk.com/robot/send?access_token=4508a9fd84f242642281cd7cf5beccc02e0bb83fad0531d3d1ef40b9fc3ada55'

# 支付宝沙箱
ALIPAY_PUBLIC = """-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAv8p3suQvEwy3dL53eSUAXjIXiXVMhjh1KX2BwpcA6znI0drdt+2i359VT/n3H5K2Gq5lfVD/aBme3+o4RRFZwrgAoKtoktZO3KkykMCouRuQCTF9cg0yaaIRzhJj3E7f+KgzZx7NjXY/YTocg6N3K/53miV2HOpc6f8kk73qfSmXan2U+dx/L0KxtucD8u6PPow01vViKtywcKTk0o3hJLT51vcc+7MA9hlQmZ6b/otlYZG56M6pCecO++KXwUIcXZILvobZfFF1EgPuMsc1lJhuknYySbh64VvnF+2lWh4klejZPZOyP0wpXL5P4IyZHozeDY79HYdcVkVKV3QMMQIDAQAB
-----END PUBLIC KEY-----"""

APP_PRIVATE = """-----BEGIN RSA PRIVATE KEY-----
MIIEpAIBAAKCAQEAv8p3suQvEwy3dL53eSUAXjIXiXVMhjh1KX2BwpcA6znI0drdt+2i359VT/n3H5K2Gq5lfVD/aBme3+o4RRFZwrgAoKtoktZO3KkykMCouRuQCTF9cg0yaaIRzhJj3E7f+KgzZx7NjXY/YTocg6N3K/53miV2HOpc6f8kk73qfSmXan2U+dx/L0KxtucD8u6PPow01vViKtywcKTk0o3hJLT51vcc+7MA9hlQmZ6b/otlYZG56M6pCecO++KXwUIcXZILvobZfFF1EgPuMsc1lJhuknYySbh64VvnF+2lWh4klejZPZOyP0wpXL5P4IyZHozeDY79HYdcVkVKV3QMMQIDAQABAoIBAQCmqJStQfXaEuHUM7Jz9gBE2jhzvRc7RxIgdKxuYHNu9C6alRq3umse8UDcF3Vz3TQbKVKNu/XFCwZwwwIUmogqWWRKOcjMWCf9PZXwDUpQWDAonPXKRsd43VmlfXuDNJMRa3AHes/Zzlgy76FZjpF/DEf4Dfd+FvWYbJrnO0/pY9jVF7eMjg0CmoJuZr0HUotiexrXzoJVMeq2o7GbnIpiXcxyYYZQuucIRzoU+hOLP4UZf+cdZ9n4wRzKTmGurRpEquJUoZZ8Jr3wMWpXacNokiVzwqK6oC6bWmg8vdKZ48i/B/WQ8SzDNMXYwepip6dQlyicVaGHFf8rhxtBGjQBAoGBAPVQmfO8cwcKLnhHPL7i9jqvWat6bKTjuK/TIfcsVbEqfuinXoEozvIyn2ktqwQIrJ/5+g64ZsvGvnTb21LNQknX9wLdRK9qTN5ThU6tqMr42LOe8RMXqPLEJzff+tk97uA2oC5bWTd+4u0UZFwV95o/Uq3f210CQY904Pl9Vt/BAoGBAMglCz5cdBfyssom9UsnNmAEhEklr54/nnQT6PXcWcIJl9b0IhH/jyXgmYkTD87VHhXMMQ/WGvQQY4zhVjzKG+nV1g2Gk33r5Ic/0R8+ivyMuAVUgAkYgW1C9PPfs6/b1oBCPcpzJcDTi4HMnb6Z2U0R/Evz1CdWonNlSABQbUhxAoGAWbJ2CEwAlzNe2HXbvURJmh2hoPSrowLs9cUyZylbz+Lk8na4NGvSd3aRGSksndX6IKiLiTRdyebKnvoA0N7ifROtauuzAJzSrHxHgwQ2crjYq5zTMxL0oIeee2y3URW3MV5n5WtbTNJlcSCCrbUOiuTae18d231GsYif9jmhOUECgYEAkRRZLCE0fk+NToAi+xE3ly5u/d71iI6xO49bJS1PWxo9GLHrKITJrTk70mMg6FsP7dkQD1yyOQzQPMTzECmpRj2dZjyRGYwvIeMeobliYmNW2XZBQVakKyGIEmesBuQifuKFjAUf7sDptXMvPYSkQfuxmRTsSn/ATkmygZfLP+ECgYAXeVkA1sXe6fElU3eY79MoS6LUXXN0PEygtDT8N9noIw/6yfG48tOdK2RIt31L8h1kYEanmEk2C3kbrPgQ6w9GgeVbpVhbhHosWKGLX9Rw6P9IspcuhbhyiSrYyIgSjzkGOgOOzwMJrqLN43a988GOLk1Hs9OKsGSKZJ2Fjo3Weg==
-----END RSA PRIVATE KEY-----"""

ALIPAY_URL = "https://openapi.alipaydev.com/gateway.do"