# Generated by Django 2.1.8 on 2019-10-06 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0002_auto_20191005_2139'),
        ('Buyer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartOne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_unit', models.CharField(default='500g', max_length=32)),
                ('count', models.IntegerField()),
                ('total_price', models.FloatField(blank=True, null=True)),
                ('status', models.IntegerField(default=1)),
                ('date', models.DateTimeField(auto_now=True)),
                ('buy_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Buyer.BuyerUser')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seller.Goods')),
            ],
        ),
    ]
