# Generated by Django 2.1.8 on 2019-10-06 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0002_auto_20191005_2139'),
        ('Buyer', '0002_cartone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_num', models.CharField(max_length=32)),
                ('order_date', models.DateTimeField(auto_now=True)),
                ('order_status', models.IntegerField(default=0)),
                ('order_total', models.FloatField(blank=True, null=True)),
                ('order_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Buyer.BuyerUser')),
            ],
        ),
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_id', models.IntegerField()),
                ('goods_name', models.CharField(max_length=32)),
                ('goods_picture', models.CharField(max_length=32)),
                ('goods_count', models.IntegerField()),
                ('goods_price', models.FloatField()),
                ('goods_total_price', models.FloatField()),
                ('status', models.IntegerField(default=0)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Buyer.Order')),
                ('store_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seller.SellerUser')),
            ],
        ),
    ]
