# Generated by Django 2.1.8 on 2019-10-05 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_num', models.CharField(max_length=10)),
                ('goods_name', models.CharField(max_length=32)),
                ('goods_price', models.FloatField()),
                ('goods_count', models.IntegerField()),
                ('goods_location', models.CharField(max_length=254)),
                ('goods_safe_date', models.IntegerField()),
                ('goods_pro_time', models.DateField()),
                ('goods_picture', models.ImageField(upload_to='seller/images')),
                ('goods_status', models.IntegerField(default=1)),
                ('goods_description', models.TextField(default='新鲜食品，好味道')),
                ('goods_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seller.SellerUser')),
            ],
            options={
                'verbose_name': '商品',
            },
        ),
        migrations.CreateModel(
            name='GoodsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=32)),
                ('description', models.TextField(blank=True, null=True)),
                ('picture', models.ImageField(upload_to='seller/images')),
            ],
        ),
        migrations.AddField(
            model_name='goods',
            name='goods_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seller.GoodsType'),
        ),
    ]
